title: Cage-based Neural Radiance Fields for Genrenlized 3D Deformation and Animation
description: Yicong Peng <sup>1</sup>, Yichao Yan
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman